Fix error due to bad call to Firestore api.As part of fixing it, the model also fixed an error in a firestore query to get documents without  a field set which is not possible. Also it updated the previously written module to add the default value to the field.
"I received the following error while running update_documents.py.

ERROR:__main__:Error updating documents: module 'google.cloud.firestore' has no attribute 'firestore'"